[pytest]
asyncio_mode = auto
testpaths =
    svc-usuarios/app/tests

addopts =
    --cov=svc-usuarios/app
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --cov-fail-under=80

filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::DeprecationWarning:jose.*

[coverage:run]
omit =
    */tests/*
    */__pycache__/*
    */migrations/*
