[pytest]
asyncio_mode = auto
testpaths =
    svc-usuarios/app/tests

addopts =
    --cov=.
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --cov-fail-under=80
    -v

filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::DeprecationWarning:jose.*
