[pytest]
asyncio_mode = auto
testpaths =
    svc-usuarios/app/tests
    svc-orcamento/app/tests
    svc-previsao/app/tests
    svc-notificacoes/app/tests

addopts =
    --cov=svc-usuarios/app
    --cov=svc-orcamento/app
    --cov=svc-previsao/app
    --cov=svc-notificacoes/app
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --cov-fail-under=80

[coverage:run]
omit =
    */tests/*
    */__pycache__/*
    */migrations/*
