sonar.projectKey=tinalmeid_python-smartbudget-api
sonar.organization=tinalmeid
sonar.projectName=python-smartbudget-api
sonar.projectVersion=1.0

sonar.sources=svc-usuarios/app,svc-orcamento/app,svc-previsao/app,svc-notificacoes/app
sonar.tests=svc-usuarios/app/tests
sonar.test.inclusions=**/tests/**,**/*_test.py,**/test_*.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/__init__.py
sonar.coverage.exclusions=svc-orcamento/**,svc-previsao/**,svc-notificacoes/**
sonar.qualitygate.wait=false

# @file Fim do arquivo sonar-project.properties
