"""cria tabela usuarios

Revision ID: 5e7376239e45
Revises: 
Create Date: 2026-04-04 23:29:50.794205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7376239e45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID gerado automaticamente'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único do usuário - usado para login'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt da senha — nunca armazenar senha pura'),
    sa.Column('nome', sa.String(length=100), nullable=True, comment='Nome completo do usuário'),
    sa.Column('renda_mensal', sa.String(length=20), nullable=True, comment='Renda mensal declarada pelo usuário'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Indica se a conta do usuário está ativa'),
    sa.Column('criado_em', sa.DateTime(), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False, comment='Data e hora da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
