# @file nginx/nginx.conf
# @description: Configuração do nginx como API Gateway do SmartBudget.
#              Define rate limiting, headers de segurança e roteamento
#              por prefixo de URL para os 4 microsserviços.
#
# @author: Tina de Almeida
# @date: Abril de 2026
# @version: 1.0.0

events {
    # Número máximo de conexões simultâneas que cada worker pode abrir ao mesmo tempo
    worker_connections 1024; # Valor padrão, pode ser ajustado conforme necessidade
}

http {
    # --- Rate Limiting ---
    # Limita 20 requisições por segundo por IP
    # Protege contra ataques de força bruta e DoS
    limit_req_zone $binary_remote_addr zone=api:10m rate=20r/s;

    # --- Upstream - Serviços de destino ---
    # Define os endereços dos microsserviços
    upstream svc_usuarios {
        server svc-usuarios:8001;
    }

    upstream svc_orcamento {
        server svc-orcamento:8002;
    }

    upstream svc_previsao {
        server svc-previsao:8003;
    }

    upstream svc_notificacoes {
        server svc-notificacoes:8004;
    }

    # --- Server Principal ---
    server {
        listen 80;
        server_name localhost;

        # --- Headers de segurança ---
        # X-Frame-Options          → proteção contra clickjacking
        # X-Content-Type-Options   → proteção contra MIME sniffing
        # X-XSS-Protection         → proteção contra XSS
        # Referrer-Policy          → proteção contra vazamento de URLs

        # Impede que o site seja carregado em um iframe
        add_header X-Frame-Options DENY;
        # Impede que o navegador execute scripts de fontes não confiáveis(adivinhe o tipo de conteúdo)
        add_header X-Content-Type-Options nosniff;
        # Protege contra ataques de Cross-Site Scripting (XSS)
        add_header X-XSS-Protection "1; mode=block";
        # Define a política de referrer
        add_header Referrer-Policy "strict-origin-when-cross-origin";

        # --- Roteamento por prefixo de URL ---
        location /v1/ {
            limit_req zone=api burst=40 nodelay;

            location /v1/auth/          { proxy_pass http://svc_usuarios;     }
            location /v1/usuarios/      { proxy_pass http://svc_usuarios;     }
            location /v1/transacoes/    { proxy_pass http://svc_orcamento;    }
            location /v1/orcamentos/    { proxy_pass http://svc_orcamento;    }
            location /v1/resumo/        { proxy_pass http://svc_orcamento;    }
            location /v1/prever-gasto/  { proxy_pass http://svc_previsao;     }
            location /v1/modelos/       { proxy_pass http://svc_previsao;     }
            location /v1/notificacoes/  { proxy_pass http://svc_notificacoes; }
            location /v1/preferencias/  { proxy_pass http://svc_notificacoes; }

            # Passa o IP real do cliente para os serviços
            proxy_set_header Host                   $host;
            proxy_set_header X-Real-IP              $remote_addr;
            proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto      $scheme;

            # Timeout
            proxy_connect_timeout                   5s;
            proxy_send_timeout                      30s;
            proxy_read_timeout                      30s;

        }

        # --- Helat Check do próprio NGINX ---
        location /health {
            return 200 '{"status": "ok", "service": "nginx", "version": "1.0.0"}';
            add_header Content-Type "application/json";
        }
    }
}

# @file Fim do arquivo nginx/nginx.conf
