"""cria schema orcamento e tabelas

Revision ID: 254493daf071
Revises:
Create Date: 2026-05-15 23:33:31.553805

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '254493daf071'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS orcamento")
    op.create_table('categorias',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('tipo', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='orcamento'
                    )
    op.create_index(op.f('ix_orcamento_categorias_id'), 'categorias', [
                    'id'], unique=False, schema='orcamento')
    op.create_table('orcamentos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('usuario_id', sa.Integer(), nullable=False),
                    sa.Column('categoria_id', sa.Integer(), nullable=False),
                    sa.Column('limite', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('mes_ano', sa.String(length=7), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['categoria_id'], ['orcamento.categorias.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('usuario_id', 'categoria_id',
                                        'mes_ano', name='uq_orcamento_usuario_categoria_mes'),
                    schema='orcamento'
                    )
    op.create_index(op.f('ix_orcamento_orcamentos_id'), 'orcamentos', [
                    'id'], unique=False, schema='orcamento')
    op.create_table('transacoes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('usuario_id', sa.Integer(), nullable=False),
                    sa.Column('categoria_id', sa.Integer(), nullable=False),
                    sa.Column('valor', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('data_transacao', sa.Date(), nullable=False),
                    sa.Column('descricao', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['categoria_id'], ['orcamento.categorias.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='orcamento'
                    )
    op.create_index(op.f('ix_orcamento_transacoes_id'), 'transacoes', [
                    'id'], unique=False, schema='orcamento')
    op.create_index('ix_transacoes_usuario_data', 'transacoes', [
                    'usuario_id', 'data_transacao'], unique=False, schema='orcamento')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transacoes_usuario_data',
                  table_name='transacoes', schema='orcamento')
    op.drop_index(op.f('ix_orcamento_transacoes_id'),
                  table_name='transacoes', schema='orcamento')
    op.drop_table('transacoes', schema='orcamento')
    op.drop_index(op.f('ix_orcamento_orcamentos_id'),
                  table_name='orcamentos', schema='orcamento')
    op.drop_table('orcamentos', schema='orcamento')
    op.drop_index(op.f('ix_orcamento_categorias_id'),
                  table_name='categorias', schema='orcamento')
    op.drop_table('categorias', schema='orcamento')
    op.execute("DROP SCHEMA IF EXISTS orcamento CASCADE")
    # ### end Alembic commands ###
